### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp2-visiteur-bacha-chat-tp2#1]
- Vous m'expliquer très bien le pattern visiteur mais dès qu'on a de la priorité on casse tout
https://github.com/PolytechLyon/isi3-tp2-visiteur-bacha-chat-tp2/blob/3d4c67f2f8cd9501cd8638f3521e39f6a2e0cd57/src/main/java/visiteurs/VisiteurInfix.java#L22-L28

C'est dommage 😭 

Les instanceof c'est un code smell. 

La priorité pourrait être information qui découle du type de Noeud ?

Sinon le reste c'est très bien.

**Comment by TheCaptainCat** [comment]
- Nous avons modifié le système de priorité. Chaque noeud a désormais la sienne.

https://github.com/PolytechLyon/isi3-tp2-visiteur-bacha-chat-tp2/blob/6b5f4903191525d5f54220dd48c5b71af566e3a6/src/main/java/visitables/Noeud.java#L3-L5

- Le visiteur infixe peut être plus générique :

https://github.com/PolytechLyon/isi3-tp2-visiteur-bacha-chat-tp2/blob/6b5f4903191525d5f54220dd48c5b71af566e3a6/src/main/java/visiteurs/VisiteurInfix.java#L14-L24

**Comment by Slashgear** [comment]
Gérer la priorité par un int, c'est bien.
Mais mettre en dur une valeur dans une classe, c'est pas terrible pour la relecture.
Niveau lisibilité, on préfèrera mettre un Enum valué sui donnera du sens à cette valeur ?

Vous comprenez ?

**Comment by TheCaptainCat** [comment]
En effet, c'est ainsi plus facile de changer les valeurs sans avoir à modifier quatre classes !

**Comment by Slashgear** [comment]
Ok
